<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adani B. Abutto (Email: aabutto@stanford.edu)">
<meta name="dcterms.date" content="2023-12-12">

<title>Replication of study ‘The curse of knowledge in reasoning about false beliefs’ by Susan A. J. Birch and Paul Bloom (2007, Psychological Science)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Final Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final Report_files/libs/quarto-html/quarto.js"></script>
<script src="Final Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Final Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final Report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final Report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#link-to-rescue-project-repository-github" id="toc-link-to-rescue-project-repository-github" class="nav-link" data-scroll-target="#link-to-rescue-project-repository-github">Link to Rescue Project Repository (GitHub)</a></li>
  <li><a href="#link-to-original-paper-github" id="toc-link-to-original-paper-github" class="nav-link" data-scroll-target="#link-to-original-paper-github">Link to Original Paper (GitHub)</a></li>
  <li><a href="#link-to-hosted-experiment-qualtrics" id="toc-link-to-hosted-experiment-qualtrics" class="nav-link" data-scroll-target="#link-to-hosted-experiment-qualtrics">Link to Hosted Experiment (Qualtrics)</a></li>
  <li><a href="#summary-of-prior-replications" id="toc-summary-of-prior-replications" class="nav-link" data-scroll-target="#summary-of-prior-replications">Summary of Prior Replications</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#power-analysis" id="toc-power-analysis" class="nav-link" data-scroll-target="#power-analysis">Power Analysis</a></li>
  <li><a href="#planned-sample" id="toc-planned-sample" class="nav-link" data-scroll-target="#planned-sample">Planned Sample</a></li>
  <li><a href="#materials" id="toc-materials" class="nav-link" data-scroll-target="#materials">Materials</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a></li>
  <li><a href="#controls" id="toc-controls" class="nav-link" data-scroll-target="#controls">Controls</a></li>
  <li><a href="#key-test-and-analysis-plan" id="toc-key-test-and-analysis-plan" class="nav-link" data-scroll-target="#key-test-and-analysis-plan">Key Test and Analysis Plan</a></li>
  <li><a href="#deviations-from-original-study-and-previous-replications" id="toc-deviations-from-original-study-and-previous-replications" class="nav-link" data-scroll-target="#deviations-from-original-study-and-previous-replications">Deviations from Original Study and Previous Replications</a></li>
  <li><a href="#methods-addendum-post-data-collection" id="toc-methods-addendum-post-data-collection" class="nav-link" data-scroll-target="#methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</a></li>
  </ul></li>
  <li><a href="#actual-sample" id="toc-actual-sample" class="nav-link" data-scroll-target="#actual-sample">Actual Sample</a>
  <ul class="collapse">
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing">Data Processing</a></li>
  <li><a href="#sample-size-n-387" id="toc-sample-size-n-387" class="nav-link" data-scroll-target="#sample-size-n-387">Sample Size (N = 387)</a></li>
  <li><a href="#demographics" id="toc-demographics" class="nav-link" data-scroll-target="#demographics">Demographics</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a></li>
  <li><a href="#results-of-control-measures" id="toc-results-of-control-measures" class="nav-link" data-scroll-target="#results-of-control-measures">Results of Control Measures</a></li>
  <li><a href="#confirmatory-analysis" id="toc-confirmatory-analysis" class="nav-link" data-scroll-target="#confirmatory-analysis">Confirmatory Analysis</a></li>
  <li><a href="#exploratory-analyses" id="toc-exploratory-analyses" class="nav-link" data-scroll-target="#exploratory-analyses">Exploratory Analyses</a></li>
  </ul></li>
  <li><a href="#summary-and-discussion-of-replication-attempt" id="toc-summary-and-discussion-of-replication-attempt" class="nav-link" data-scroll-target="#summary-and-discussion-of-replication-attempt">Summary and Discussion of Replication Attempt</a>
  <ul class="collapse">
  <li><a href="#mini-meta-analysis" id="toc-mini-meta-analysis" class="nav-link" data-scroll-target="#mini-meta-analysis">Mini Meta Analysis</a></li>
  <li><a href="#commentary" id="toc-commentary" class="nav-link" data-scroll-target="#commentary">Commentary</a></li>
  </ul></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of study ‘The curse of knowledge in reasoning about false beliefs’ by Susan A. J. Birch and Paul Bloom (2007, Psychological Science)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adani B. Abutto (Email: aabutto@stanford.edu) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 12, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Ample psychological literature has investigated and discussed the onset and development of human reasoning about others’ beliefs and knowledge states. Various scholars and findings have suggested that young children struggle considerably with false-belief reasoning, that is, reasoning about others’ beliefs in cases where those beliefs conflict with reality. Birch and Bloom’s (2007) seminal study examined whether adults’ struggles in “false-belief reasoning” are akin to children’s when sufficiently sensitive measures are used. Indeed, their results indicated that young adults’ (<em>N</em> = 155 college students) reasoning about another person’s (false) belief about the world can be compromised by manipulating their knowledge about an event’s outcome as well as the plausibility of the event in question. In sum, this finding suggested that while children may have difficulties ignoring their knowledge when reasoning from the perspective of an unknowing agent, adults may experience their knowledge interfering with their false-belief reasoning ability in similar ways.</p>
<p><strong>Figure 1.</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Screenshot%202023-10-22%20at%2015.20.40.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure taken from Birch and Bloom (2007); questionnaire item prompting participants to respond by indicating probabilities between 0 and 100. Color-word labels (red, green, purple, blue) are included in the figure for interpretability and were not shown to participants in the study.</figcaption>
</figure>
</div>
<p>Birch and Bloom’s experimental study employed a simple four-step procedure, using a modified version of a classic displacement task (see, e.g., Wimmer &amp; Perner, 1983). Figure 1 shows the task as presented to participants in one of the three experimental conditions. The procedure was highly similar across conditions: In the first step, all participants were shown a picture of a girl, Vicki, holding a violin in a living room with a sofa and four containers of different colors. Participants were then told that once Vicki finished playing, she placed her violin in a blue container and goes outside playing. Thereafter, participants were shown a text and picture conveying that Vicki’s sister, Denise, came in, moved the violin, and rearranged the colored containers. To this end, participants were shown another short text, this time varying by experimental condition: “While Vicki is outside playing, her sister, Denise moves the violin to […]”</p>
<ul>
<li><p><em>Ignorance</em> condition: “[…] another container.” (no knowledge of outcome; no interference with false-belief reasoning)</p></li>
<li><p><em>Knowledge-plausible</em> condition: “[…] the red container.” (knowledge of placement in same location but different container; interference with false-belief reasoning)</p></li>
<li><p><em>Knowledge-implausible</em> condition: “[…] the purple container.” (knowledge of placement in different location and different container; no (or less) interference with false-belief reasoning)</p></li>
</ul>
<p>Then, upon conclusion of the story, participants were asked to respond to a single question: “When Vicki returns, she wants to play her violin. What are the chances Vicki will first look for her violin in each of the [colored] containers?” Respondents were asked to give their answers in percentages by filling out four separate response fields (i.e., one for each of the four containers).</p>
<p>Given that the study involved only simple text and picture material as well as a single-page questionnaire, I do not anticipate any major challenges in the reproduction and use of study materials. I expect that all experimental manipulations, respondent instructions, and measures can be administered without issue by using <em>Qualtrics</em>’ in-built survey functions. Notably, however, it seems that Birch and Bloom (2007) administered their questionnaire in physical form. It is possible that when using the <em>Qualtrics</em> platform, it is not achievable to display the figure text and probability response fields in the exact same layout as in the original study (e.g., field size and location).</p>
<p>However, this slight limitation in replicating the study materials should not impact the overall replication quality in fundamental ways. Indeed, in light of the COVID-19 pandemic, numerous researchers have started creating and employing digital versions of classic “theory of mind” (ToM) tasks that have typically been administered in person. The findings of such online studies (e.g., in terms of task success rates by age bracket) are generally comparable to the findings of the corresponding in-person research (see Livingston et al., 2021, for an example).</p>
</section>
<section id="link-to-rescue-project-repository-github" class="level2">
<h2 class="anchored" data-anchor-id="link-to-rescue-project-repository-github">Link to Rescue Project Repository (GitHub)</h2>
<p><a href="https://github.com/psych251/birch2007_2_rescue/">Rescue project repository on GitHub</a></p>
</section>
<section id="link-to-original-paper-github" class="level2">
<h2 class="anchored" data-anchor-id="link-to-original-paper-github">Link to Original Paper (GitHub)</h2>
<p><a href="https://github.com/psych251/birch2007_2_rescue/tree/main/original_paper">Original paper (Birch &amp; Bloom, 2007) on GitHub</a></p>
</section>
<section id="link-to-hosted-experiment-qualtrics" class="level2">
<h2 class="anchored" data-anchor-id="link-to-hosted-experiment-qualtrics">Link to Hosted Experiment (Qualtrics)</h2>
<p><a href="https://stanforduniversity.qualtrics.com/jfe/form/SV_egPpG0CfiIZAKPk?PROLIFIC_PID=6532e945721c66a08685dbaa&amp;STUDY_ID=6539a3a6f3653a31f4561148&amp;SESSION_ID=03e1hesve6nm">Study paradigm on Qualtrics</a></p>
</section>
<section id="summary-of-prior-replications" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-prior-replications">Summary of Prior Replications</h2>
<p>There are three notable differences between the original study (Birch &amp; Bloom, 2007) and the first replication study by Borchers (2018, see <a href="https://rpubs.com/lrborchers/450894" class="uri">https://rpubs.com/lrborchers/450894</a>). The first lies in the replication study omitting one of the three experimental conditions (<em>knowledge-implausible</em>)<em>.</em> Borchers justifies this in pointing out that the authors did not report significant differences between the <em>knowledge-plausible</em> group and the <em>ignorance</em> group. However, given that Birch and Bloom (2007) did report a lack of a difference between the <em>ignorance</em> and <em>knowledge-implausible</em> groups as one of two key findings — indicating that knowledge alone does not appear to be the sole factor biasing adults’ false-belief reasoning —, I plan to diverge from Borchers’ approach and include this condition in the present study.</p>
<p>Second, the sample of the original study consisted of undergraduate students at Yale, whereas Borchers’ sample consisted of MTurk workers. Borchers did ask respondents to indicate their education levels but remarked that given this circumstance, there would likely be a difference in education between the original group and the MTurk sample.</p>
<p>Third, Borchers’ study was conducted online rather than in person, which meant that stimuli had to be adapted and were not perfectly equivalent to the original materials. It should also be noted that Borchers asked participants whether they were colorblind and excluded people in this category — Birch and Bloom did not report whether they did so.</p>
<p>Finally, Borchers raised a crucial issue prior to her data collection: Given that participants were asked to write down their probability estimates in a simple text box, it was possible for them to make typing or calculation errors, resulting in the sum of all response fields to add up to less (or more) than 100%. Indeed, in Borchers’ data, there were <em>n</em> = 8 such cases (<em>n</em> = 4 in each condition). Borchers reported that she thus conducted her analysis twice — once including these cases, and once excluding them — and that the results did not differ across subsamples. Nevertheless, this circumstance led to a slight reduction in her sample size and statistical power. The present study will avoid this by integrating an input check in the survey (e.g., having a message pop up on the respective Qualtrics page if respondents’ probability values don’t add up to 100%).</p>
<p>Notably, there exists also an earlier replication conducted by Bridgers (n.d., see <a href="https://docs.google.com/document/d/1fSARliH5QKadGy3UElC00ehgwr2LLQbey-uzb1RPv0A/edit" class="uri">https://docs.google.com/document/d/1fSARliH5QKadGy3UElC00ehgwr2LLQbey-uzb1RPv0A/edit</a>). Bridgers’ replication was highly similar to Borchers’, the only difference being that Bridgers incoporated all three conditions and employed slightly adapted versions of Birch and Bloom’s (2007) story stimuli.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set echo = TRUE (showing code) as default for all code chunks</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> T)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Import relevant libraries</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse); <span class="fu">library</span>(ggplot2); <span class="fu">library</span>(car); <span class="fu">library</span>(effsize); <span class="fu">library</span>(qualtRics); <span class="fu">library</span>(readxl); <span class="fu">library</span>(patchwork); <span class="fu">library</span>(ggpubr); <span class="fu">library</span>(metafor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ ggplot2 3.4.4     ✔ purrr   1.0.2
✔ tibble  3.2.1     ✔ dplyr   1.1.4
✔ tidyr   1.3.0     ✔ stringr 1.5.1
✔ readr   2.1.2     ✔ forcats 0.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: metadat</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: numDeriv</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Loading the 'metafor' package (version 4.4-0). For an
introduction to the package please type: help(metafor)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'metafor'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    vif</code></pre>
</div>
</div>
<section id="power-analysis" class="level3">
<h3 class="anchored" data-anchor-id="power-analysis">Power Analysis</h3>
<p>The original effect size Birch and Bloom (2007) reported was <em>d</em> = 0.472 (<em>t</em>(105) = -2.42, <span class="math inline">\(p_{rep}\)</span> = .95). Neither Bridgers (n.d.) nor Borchers (2018) replicated this effect: <em>t</em>(149.58) = -1.20, <em>p</em> = 0.231, and <em>t</em>(70.25) = -0.65, <em>p</em> = .518, respectively. In the former case (Bridgers), the sample size (<em>N</em> = 225) considerably exceeded that of the original authors (<em>N</em> = 155). In the latter case (Borchers), the sample size (<em>N</em> = 73) was smaller compared to that of the original authors.</p>
<p>In planning her replication study, <a href="https://rpubs.com/lrborchers/450894">Borchers (2018)</a> ran an a-priori power analysis and reported that “[we] would need 24 participants per condition to achieve 80% power, 32 participants per condition to achieve 90% power, and 40 participants per condition to achieve 95% power.”</p>
<p>In contrast, in the earlier replication by <a href="https://docs.google.com/document/d/1fSARliH5QKadGy3UElC00ehgwr2LLQbey-uzb1RPv0A/edit">Bridgers (n.d.)</a>, it was reported that “[…] to detect [the original] effect size with 80%, 90%, and 95% power, the sample size would need to be 71 participants per condition, 95 participants per condition, or 118 participants per condition, respectively.”</p>
<p>In re-running the above power analysis, I found that required sample sizes would indeed be 71, 95, and 118 per condition to achieve 80%, 90%, and 95% power, respectively:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 80% power</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> .<span class="dv">472</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> .<span class="dv">80</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 71.43496
          delta = 0.472
             sd = 1
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># 90% power</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> .<span class="dv">472</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> .<span class="dv">90</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 95.29902
          delta = 0.472
             sd = 1
      sig.level = 0.05
          power = 0.9
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># 95% power</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> .<span class="dv">472</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> .<span class="dv">95</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 117.6266
          delta = 0.472
             sd = 1
      sig.level = 0.05
          power = 0.95
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>Unfortunately, there exists no meta-analysis that could provide a more precise estimate of the effect size, and the pilot data obtained as part of the present project was too limited in size as to be informative (<em>N</em> &lt; 10, non-naive participants). In short, I do not have strong prior information about the likely effect size.</p>
<p>Given all of the above, I will follow <a href="https://dx.doi.org/10.2139/ssrn.2259879">Simonsohn’s (2014)</a> recommendation of “[obtaining] 2.5 times as many observations as the original study to obtain about 80% power to reject a detectable effect,” (p.&nbsp;14) if the true effect is zero. Thus, <span class="math inline">\(N_{planned}=N_{original}*2.5 = 155*2.5=387\)</span>.</p>
<p>Given that I estimate my study to take only a few minutes, and plan to use an hourly pay of $10, I anticipate it to be feasible to recruit a sample size of <em>N</em> = 387 while staying within budget (<span class="math inline">\(N_{planned}*pay = 387*(\frac{10}{60}*\$3)=\$194\)</span>).</p>
<p>With <em>N</em> = 387, assuming an attenuated effect that is half the size of the original (<em>d</em> = 0.236), power will be ~60% (one-sided test):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> .<span class="dv">236</span>, <span class="at">n =</span> <span class="dv">129</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="cn">NULL</span>,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">alternative =</span> <span class="st">"one.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 129
          delta = 0.236
             sd = 1
      sig.level = 0.05
          power = 0.5969635
    alternative = one.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>Figure 2 below shows a more comprehensive overview of the interplay between effect size and required sample size:</p>
<p><strong>Figure 2.</strong></p>
<p><img src="images/powerplot.png" class="img-fluid"></p>
<p><em>Note</em>. Graph generated in G*Power: Required sample size to detect a given effect of size <em>d</em> with 80% power.</p>
</section>
<section id="planned-sample" class="level3">
<h3 class="anchored" data-anchor-id="planned-sample">Planned Sample</h3>
<p>To achieve similar education-level demographics as Birch and Bloom (2007), I will use a pre-screener to recruit only adults enrolled in college. Additionally, I will pre-screen for colorblindness. Lastly, I will pre-screen for Prolific respondents with high approval rates (indicating that their participation in previous Prolific studies was of high quality). I propose to recruit <em>N</em> = 387 participants (<em>n</em> = 129 per condition) fitting the above criteria and will terminate data collection once this number is reached.</p>
</section>
<section id="materials" class="level3">
<h3 class="anchored" data-anchor-id="materials">Materials</h3>
<p>Materials will be employed as reported by Borchers (2018): “This study [will use] a colored figure depicting Vicki, her violin, a sofa, and four containers (ordered: blue, purple, red, green) on the top panel and her sister, the violin, a sofa, and the containers (reordered: red, green, purple, blue) on the bottom panel. All participants [will be] shown the following text (manipulations shown in brackets): ’This is Vicki. She finishes playing her violin and puts it in the blue container. Then she goes outside to play. While Vicki is outside playing, her sister, Denise, moves the violin…</p>
<ul>
<li><p>[<em>ignorance</em>] …to another container</p></li>
<li><p>[<em>knowledge-plausible</em>] …to the red container</p></li>
<li><p>[<em>knowledge-implausible</em>] …to the purple container</p></li>
</ul>
<p>Then Denise rearranges the containers in the room until the room looks like the picture below. When Vicki returns, she wants to play her violin. What are the chances Vicki will first look for her violin in each of the above containers? Write your answers in percentages in the spaces provided under each container.’ All participants will receive the same figure with modifications to the text according to their condition (described above).”</p>
<p>Given that the materials made available by Birch and Bloom’s (2007) are black-and-white, I contacted Borchers to obtain her colored figure. Borchers shared said figure, and I added only minor adaptations, increasing the in-figure text size to make it more readable (see <a href="https://github.com/psych251/birch2007_2_rescue/tree/main/stimuli" class="uri">https://github.com/psych251/birch2007_2_rescue/tree/main/stimuli</a>).</p>
</section>
<section id="procedure" class="level3">
<h3 class="anchored" data-anchor-id="procedure">Procedure</h3>
<p>My procedure will largely match that of Borchers: “[I will employ] a between-subjects design and participants will be randomly assigned to the <em>ignorance</em> or <em>knowledge-plausible</em> condition at the beginning of the study. After reading the corresponding prompt, all participants will report on their perceived probability that Vicki will look in each of the four containers for her violin.”</p>
<p>The main difference is that the present study will include all three conditions used by Birch and Bloom (2007) rather than merely <em>knowledge-plausible</em> and <em>ignorance</em> as in Borchers (2018). Additionally, I formatted response fields to be displayed side-by-side right beneath the experimental manipulation figure, and moved demographic questions to the very end of the study.</p>
</section>
<section id="controls" class="level3">
<h3 class="anchored" data-anchor-id="controls">Controls</h3>
<p>In addition to pre-screening for Prolific respondents with color vision, college enrollment, and ≥ Prolific 99% approval rates, I will include a response check ensuring that participants’ probability estimates add up to (roughly) 100% across the four response fields. No other control measures will be used.</p>
</section>
<section id="key-test-and-analysis-plan" class="level3">
<h3 class="anchored" data-anchor-id="key-test-and-analysis-plan">Key Test and Analysis Plan</h3>
<p>The main analysis of interest is the comparison between the <em>ignorance</em> and <em>knowledge-plausible</em> groups in terms of their average probability for Vicky to look for her violin in the “red container” (i.e., the container residing in the same physical location as where Vicki originally placed the violin). The hypothesis — in line with the effect reported by Birch and Bloom (2007) — is that, on average, participants in the <em>knowledge-plausible</em> group will report significantly higher probabilities that Vicky will look in the “red container” than participants in the <em>ignorance</em> condition. This is because in the <em>knowledge-plausible</em> condition, participants’ prior knowledge of the event outcome (that the violin was placed in the “red container”) in combination with the plausibility of the event (that Vicky will look in the “red container” because after rearrangement of the room, it is in the same physical location as the “blue container,” which is where she put her violin originally) is hypothesized to interfere with their ability to reason from Vicky’s (unknowing) perspective.</p>
<p>To test for (the replication of) this effect, I will conduct an independent samples t-test, matching the procedure followed by Birch and Bloom (2007), Bridgers (n.d.), and Borchers (2018). Cohen’s <em>d</em> will also be calculated.</p>
<p>Secondly, related to the main effect of interest above, Birch and Bloom (2007) also reported that</p>
<p>Moreover, for exploratory purposes, I will conduct three more independent samples t-tests: One to compare the reported probability for the “red container” between the <em>ignorance</em> and <em>knowledge-implausible</em> groups (anticipating no sig. difference as per Birch &amp; Bloom), another to compare <em>ignorance and knowledge-plausible</em> on their “blue container” probability judgments (anticipating lower ratings in knowledge-plausible as per Birch &amp; Bloom; <em>d</em> = 0.459), and a final one to compare <em>ignorance</em> and <em>knowledge-implausible</em> groups on their “blue container” probability judgments (anticipating no sig. difference as per Birch &amp; Bloom).</p>
</section>
<section id="deviations-from-original-study-and-previous-replications" class="level3">
<h3 class="anchored" data-anchor-id="deviations-from-original-study-and-previous-replications">Deviations from Original Study and Previous Replications</h3>
<p>Birch and Bloom’s (2007) study was conducted in person, and Bridgers (n.d.) and Borchers (2018) conducted their studies on MTurk. The present study will differ from all three in that it will be run on <em>Qualtrics</em> (<a href="http://qualtrics.com/" class="uri">http://qualtrics.com/</a>), with the sample being recruited from <em>Prolific</em> (<a href="https://prolific.co/" class="uri">https://prolific.co/</a>). The number of participants per condition will exceed that of Bridgers (<em>N</em> = 225), Borchers (<em>N</em> = 73) as well as Birch and Bloom (<em>N</em> = 155 total). The setting and procedure will match that of Borchers and Bridgers and deviate from Birch and Bloom (2007) in being set online rather than in person. My survey will incorporate the same “response check” reminder as Borchers (2018), reminding participants that their probability estimates should (roughly) add up to 100% across the four response fields. Finally, the present analysis plan matches that of all three prior studies. I anticipate none of the above deviations to make a crucial difference in the effect estimation.</p>
</section>
<section id="methods-addendum-post-data-collection" class="level3">
<h3 class="anchored" data-anchor-id="methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</h3>
<p>Although the full planned sample size was reached (<em>N</em> = 387 participants), a total of <em>n</em> = 13 participants had to be excluded from analysis. With that, the final sample size was slightly smaller than anticipated. Other than that, there is no methods addendum to be made now that data collection has been concluded.</p>
<section id="differences-from-pre-data-collection-methods-plan" class="level4">
<h4 class="anchored" data-anchor-id="differences-from-pre-data-collection-methods-plan">Differences from pre-data collection methods plan</h4>
<p>None.</p>
</section>
</section>
</section>
<section id="actual-sample" class="level2">
<h2 class="anchored" data-anchor-id="actual-sample">Actual Sample</h2>
<p>Below, I provide my data processing pipeline and thereafter describe my sample size, demographics, and data exclusions based on the rules spelled out in my analysis plan.</p>
<section id="data-processing" class="level3">
<h3 class="anchored" data-anchor-id="data-processing">Data Processing</h3>
<ol type="1">
<li>Read in csv. data in R (deidentified data set available under <a href="https://github.com/psych251/birch2007_2_rescue/tree/main/data" class="uri">https://github.com/psych251/birch2007_2_rescue/tree/main/data</a>)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>final_data_raw <span class="ot">&lt;-</span> <span class="fu">read_survey</span>(<span class="st">"/Users/ottuba/birch2007_2_rescue/data/final_data/Birch+&amp;+Bloom+replication_December+7,+2023_11.14.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Remove identifying data and other unneeded columns (e.g., date/time, response times)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Establish which columns to filter for</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>selected_columns <span class="ot">&lt;-</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">"consent_form"</span>, <span class="st">"FL_16_DO"</span>, <span class="st">"age"</span>, <span class="st">"high_school"</span>, <span class="st">"gender"</span>, <span class="st">"colorblindness"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"red_knowplausible"</span>, <span class="st">"green_knowplausible"</span>, <span class="st">"purple_knowplausible"</span>, <span class="st">"blue_knowplausible"</span>, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"red_knowimplausible"</span>, <span class="st">"green_prob"</span>, <span class="st">"purple_prob"</span>, <span class="st">"blue_knowimplausible"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"red_ignorance"</span>, <span class="st">"green_ignorance"</span>, <span class="st">"purple_ignorance"</span>, <span class="st">"blue_ignorance"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>final_data_tidy <span class="ot">&lt;-</span> final_data_raw <span class="sc">%&gt;%</span> <span class="co"># Filter to keep only columns established above</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Finished <span class="sc">!=</span> <span class="st">"FALSE"</span>, <span class="co"># Exclude participants who didn't finish</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>         FL_16_DO <span class="sc">!=</span> <span class="st">"NA"</span>, <span class="co"># Exclude participants who weren't assigned condition</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>         PID <span class="sc">!=</span> <span class="st">"NA"</span>, <span class="co"># Exclude people w/o Prolific ID (my own test runs)</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>         PID <span class="sc">!=</span> <span class="st">"a"</span>, <span class="co"># Exclude people with random Prolific ID (my own test runs)</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"TA"</span>, PID)) <span class="sc">%&gt;%</span>  <span class="co"># Exclude TA submissions</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(selected_columns)) <span class="co"># Filter to keep only columns established above</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show first few rows of data set</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(final_data_tidy),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">table.attr =</span> <span class="st">"class=</span><span class="sc">\"</span><span class="st">striped</span><span class="sc">\"</span><span class="st">"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">format =</span> <span class="st">"html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="striped table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">consent_form</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">FL_16_DO</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">high_school</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">gender</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">colorblindness</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">red_knowplausible</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">green_knowplausible</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">purple_knowplausible</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">blue_knowplausible</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">red_knowimplausible</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">green_prob</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">purple_prob</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">blue_knowimplausible</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">red_ignorance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">green_ignorance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">purple_ignorance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">blue_ignorance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I agree</td>
<td style="text-align: left;">cond_know_plausible</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">I agree</td>
<td style="text-align: left;">cond_know_implausible</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I agree</td>
<td style="text-align: left;">cond_know_implausible</td>
<td style="text-align: right;">26</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">I agree</td>
<td style="text-align: left;">cond_know_plausible</td>
<td style="text-align: right;">21</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Non-binary / other</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I agree</td>
<td style="text-align: left;">cond_ignorance</td>
<td style="text-align: right;">42</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">I agree</td>
<td style="text-align: left;">cond_ignorance</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Non-binary / other</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="sample-size-n-387" class="level3">
<h3 class="anchored" data-anchor-id="sample-size-n-387">Sample Size (N = 387)</h3>
<p>A total of <em>N</em> = 387 completed the survey. All of them had U.S. IP addresses and a ≥ 99% approval rating on Prolific.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count rows of data (1 row per participant)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(final_data_tidy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 387</code></pre>
</div>
</div>
</section>
<section id="demographics" class="level3">
<h3 class="anchored" data-anchor-id="demographics">Demographics</h3>
<p>There were <em>n =</em> 128-130 participants per condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run frequency statistics over randomizer variable</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(final_data_tidy<span class="sc">$</span>FL_16_DO)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>final_data_tidy$FL_16_DO : FL_16 - Block Randomizer - Display Order 
       n  missing distinct 
     387        0        3 
                                                                            
Value             cond_ignorance cond_know_implausible   cond_know_plausible
Frequency                    130                   129                   128
Proportion                 0.336                 0.333                 0.331</code></pre>
</div>
</div>
<p>The mean age was about 28 years (<em>SD</em> = 9.54, range = 18-74). The sample skewed heavily toward younger years. Given that I pre-screened for participants enrolled in college, this was expected.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run standard descriptive statistics over age variable</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(final_data_tidy<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars   n  mean   sd median trimmed  mad min max range skew kurtosis   se
X1    1 387 28.18 9.54     25   26.56 7.41  18  74    56 1.62     2.79 0.48</code></pre>
</div>
</div>
<p>All but one participant (<em>N</em> = 386) have completed high school and are presently enrolled in college. This was expected given that I pre-screened for participants enrolled in college.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run frequency statistics over high school variable</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(final_data_tidy<span class="sc">$</span>high_school)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>final_data_tidy$high_school : Have you completed high school? 
       n  missing distinct 
     387        0        2 
                      
Value         No   Yes
Frequency      1   386
Proportion 0.003 0.997</code></pre>
</div>
</div>
<p>The gender distribution was close to 50/50.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run frequency statistics over gender variable</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(final_data_tidy<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>final_data_tidy$gender : What is your gender? 
       n  missing distinct 
     387        0        4 
                                                                   
Value                  Female               Male Non-binary / other
Frequency                 190                177                 19
Proportion              0.491              0.457              0.049
                             
Value       Prefer not to say
Frequency                   1
Proportion              0.003</code></pre>
</div>
</div>
<p>A total of <em>n</em> = 2 participants indicated they were colorblind, despite the pre-screener.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run frequency statistics over colorblindness variable</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(final_data_tidy<span class="sc">$</span>colorblindness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>final_data_tidy$colorblindness : Are you color blind? 
       n  missing distinct 
     387        0        2 
                      
Value         No   Yes
Frequency    385     2
Proportion 0.995 0.005</code></pre>
</div>
</div>
<p>Based on the above, in a first step, I excluded a total of <em>n</em> = 2 participants from analysis due to being colorblind, and <em>n</em> = 1 participant due to not having completed high school/not being in college. After these exclusions, the remaining sample size was <em>N</em> = 384.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>final_data_tidy <span class="ot">=</span> final_data_tidy <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(high_school <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="co"># Keep only participants who completed high school</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>         colorblindness <span class="sc">==</span> <span class="st">"No"</span>, <span class="co"># Keep only participants with color vision</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>         consent_form <span class="sc">==</span> <span class="st">"I agree"</span>) <span class="co"># Keep only participants who gave consent</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<ol type="1">
<li>Reformat data</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>final_data_tidy <span class="ot">&lt;-</span> final_data_tidy <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">green_knowimplausible =</span> green_prob,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">purple_knowimplausible  =</span> purple_prob) <span class="co"># Rename columns to match others</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>final_data_tidy <span class="ot">&lt;-</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  final_data_tidy <span class="sc">%&gt;%</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">subid =</span> <span class="fu">row.names</span>(.)) <span class="sc">%&gt;%</span> <span class="co"># Subject ID equal to row number</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(measurement, probability_pct,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>         red_knowplausible<span class="sc">:</span>blue_ignorance) <span class="sc">%&gt;%</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(measurement, <span class="fu">c</span>(<span class="st">"color"</span>, <span class="st">"condition"</span>)) <span class="co"># Group probability values and conditions into single columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: attributes are not identical across measure variables; they will be
dropped</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Spread the data</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>final_data <span class="ot">=</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  final_data_tidy <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(color, probability_pct) <span class="sc">%&gt;%</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.)) <span class="co"># Filter out rows with missing values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Exclude participants whose probability estimates did not sum up to (roughly) 100% (± 5%).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>final_data <span class="ot">&lt;-</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  final_data <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_sum =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., blue, green, purple, red))) <span class="sc">%&gt;%</span> <span class="co"># Calculate probability judgment sums for each participant</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">deviation_from_100 =</span> <span class="fu">abs</span>(total_sum <span class="sc">-</span> <span class="dv">100</span>)) <span class="sc">%&gt;%</span> <span class="co"># New column: Deviation from 100</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">within_tolerance =</span> total_sum <span class="sc">&gt;=</span> <span class="dv">95</span> <span class="sc">&amp;</span> total_sum <span class="sc">&lt;=</span> <span class="dv">105</span>) <span class="co"># New column: Is participant's probability judgment sum within 5 percentage points of 100?</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(final_data<span class="sc">$</span>deviation_from_100) <span class="co"># Show frequencies of deviations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>final_data$deviation_from_100 
       n  missing distinct     Info     Mean      Gmd 
     384        0        7    0.098   0.4844    0.952 
                                                    
Value          0     1     5    10    25    30    50
Frequency    371     1     2     7     1     1     1
Proportion 0.966 0.003 0.005 0.018 0.003 0.003 0.003

For the frequency table, variable is rounded to the nearest 0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude participants who were more than 5 percentage points away from 100</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>final_data <span class="ot">&lt;-</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  final_data <span class="sc">%&gt;%</span> </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(deviation_from_100 <span class="sc">&lt;=</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">"FL_16_DO"</span>))</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(final_data),</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">table.attr =</span> <span class="st">"class=</span><span class="sc">\"</span><span class="st">striped</span><span class="sc">\"</span><span class="st">"</span>,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">format =</span> <span class="st">"html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="striped table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">consent_form</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">high_school</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">gender</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">colorblindness</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">subid</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">condition</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">blue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">green</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">purple</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">red</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total_sum</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviation_from_100</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">within_tolerance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I agree</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">218</td>
<td style="text-align: left;">ignorance</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">I agree</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">302</td>
<td style="text-align: left;">ignorance</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I agree</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">309</td>
<td style="text-align: left;">ignorance</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">I agree</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">337</td>
<td style="text-align: left;">ignorance</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I agree</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">368</td>
<td style="text-align: left;">ignorance</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">I agree</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">89</td>
<td style="text-align: left;">ignorance</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">TRUE</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>After the above exclusions (<em>n</em> = 10), the final <em>N</em> for analysis was 374. The total <em>n</em> per condition was not affected systematically.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(final_data<span class="sc">$</span>condition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>final_data$condition 
       n  missing distinct 
     374        0        3 
                                                          
Value            ignorance knowimplausible   knowplausible
Frequency              123             127             124
Proportion           0.329           0.340           0.332</code></pre>
</div>
</div>
</section>
<section id="results-of-control-measures" class="level3">
<h3 class="anchored" data-anchor-id="results-of-control-measures">Results of Control Measures</h3>
<p>None.</p>
</section>
<section id="confirmatory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="confirmatory-analysis">Confirmatory Analysis</h3>
<section id="descriptive-statistics" class="level4">
<h4 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h4>
<p>The table below shows descriptive statistics (<em>N, M</em>, <em>SD</em>) for probability ratings relating to the four containers (red, blue, green, purple) by condition (ignorant, knowledge-implausible, knowledge-implausible).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run descriptive statistics for probability judgments over each container</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(final_data <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_red =</span> <span class="fu">mean</span>(red),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_red =</span> <span class="fu">sd</span>(red),</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_blue =</span> <span class="fu">mean</span>(blue),</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_blue =</span> <span class="fu">sd</span>(blue),</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_green =</span> <span class="fu">mean</span>(green),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_green =</span> <span class="fu">sd</span>(green),</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_purple =</span> <span class="fu">mean</span>(purple),</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_purple =</span> <span class="fu">sd</span>(purple)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">table.attr =</span> <span class="st">"class=</span><span class="sc">\"</span><span class="st">striped</span><span class="sc">\"</span><span class="st">"</span>,</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">format =</span> <span class="st">"html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="striped table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">condition</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_red</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd_red</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_blue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd_blue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_green</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd_green</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_purple</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd_purple</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ignorance</td>
<td style="text-align: right;">20.49</td>
<td style="text-align: right;">16.75</td>
<td style="text-align: right;">59.50</td>
<td style="text-align: right;">30.60</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: right;">11.43</td>
<td style="text-align: right;">9.60</td>
<td style="text-align: right;">11.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">knowimplausible</td>
<td style="text-align: right;">18.03</td>
<td style="text-align: right;">18.57</td>
<td style="text-align: right;">64.08</td>
<td style="text-align: right;">29.08</td>
<td style="text-align: right;">6.56</td>
<td style="text-align: right;">8.74</td>
<td style="text-align: right;">11.37</td>
<td style="text-align: right;">17.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">knowplausible</td>
<td style="text-align: right;">23.97</td>
<td style="text-align: right;">20.33</td>
<td style="text-align: right;">65.69</td>
<td style="text-align: right;">26.35</td>
<td style="text-align: right;">5.06</td>
<td style="text-align: right;">8.39</td>
<td style="text-align: right;">5.33</td>
<td style="text-align: right;">9.17</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="key-test" class="level4">
<h4 class="anchored" data-anchor-id="key-test">Key Test</h4>
<p>The output below shows an independent samples t-test comparing participants’ probability judgments for the “red” container across the <em>Ignorant</em> and <em>knowledge-plausible</em> conditions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(red <span class="sc">~</span> condition,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> final_data[final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"knowimplausible"</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  red by condition
t = -1.4687, df = 237.01, p-value = 0.1432
alternative hypothesis: true difference in means between group ignorance and group knowplausible is not equal to 0
95 percent confidence interval:
 -8.147654  1.187780
sample estimates:
    mean in group ignorance mean in group knowplausible 
                   20.48780                    23.96774 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>effsize<span class="sc">::</span><span class="fu">cohen.d</span>(final_data<span class="sc">$</span>red[final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"ignorance"</span>], </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>                 final_data<span class="sc">$</span>red[final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"knowplausible"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Cohen's d

d estimate: 0.09217616 (negligible)
95 percent confidence interval:
      lower       upper 
-0.08347266  0.26782498 </code></pre>
</div>
</div>
</section>
<section id="graphical-comparison" class="level4">
<h4 class="anchored" data-anchor-id="graphical-comparison">Graphical Comparison</h4>
<p>The graph below visualizes the mean differences in participants’ probability judgments relating to the “red container,” comparing the <em>ignorant</em> and <em>knowledge-plausible</em> groups across the original study (Birch &amp; Bloom, 2007)<em>,</em> 1st replication (Borchers, 2018), and the present study. Bridgers (n.d.) did not report full information on the relevant mean and SD values, hence this data is not included in the comparison below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hardcode new data frame based on information in Birch &amp; Bloom (2007)</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>birch_bloom_data <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">condition =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Ignorance"</span>, <span class="dv">4</span>),</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"Knowledge-Plausible"</span>, <span class="dv">4</span>),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"Knowledge-Implausible"</span>, <span class="dv">4</span>)),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">container =</span> <span class="fu">c</span>(<span class="st">"blue"</span>,</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>                <span class="st">"red"</span>,</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>                <span class="st">"purple"</span>,</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>                <span class="st">"green"</span>), </span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability_percent =</span> <span class="fu">c</span>(<span class="dv">71</span>, <span class="dv">23</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="co"># Means for ignorance</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">59</span>, <span class="dv">34</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="co"># Means for knowledge plausible</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">73</span>, <span class="dv">19</span>, <span class="dv">6</span>, <span class="dv">3</span>), <span class="co"># Means for knowledge implausible</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">standard_deviation =</span> <span class="fu">c</span>(<span class="dv">26</span>, <span class="dv">22</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="co"># SDs for ignorance</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">27</span>, <span class="dv">25</span>, <span class="dv">5</span>, <span class="dv">7</span>,  <span class="co"># SDs for knowledge plausible</span></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">29</span>, <span class="dv">21</span>, <span class="dv">16</span>, <span class="dv">5</span>), <span class="co"># SDs for knowledge implausible</span></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">52</span>, <span class="dv">12</span>)) <span class="co"># 52 participants in each condition</span></span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">standard_error =</span> standard_deviation <span class="sc">/</span> <span class="fu">sqrt</span>(n)) <span class="co"># Calculate SE</span></span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a>filtered_birch_bloom_data <span class="ot">=</span> birch_bloom_data <span class="sc">%&gt;%</span></span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(container <span class="sc">==</span> <span class="st">"red"</span>,</span>
<span id="cb54-22"><a href="#cb54-22" aria-hidden="true" tabindex="-1"></a>         condition <span class="sc">!=</span> <span class="st">"Knowledge-Implausible"</span>) <span class="co"># Keep only data relating to red container judgments</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Birch &amp; Bloom data for red container judgments</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(filtered_birch_bloom_data,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>         <span class="fu">aes</span>(<span class="at">x =</span> condition, <span class="at">y =</span> probability_percent, <span class="at">fill =</span> condition)) <span class="sc">+</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">"dodge"</span>, <span class="at">stat=</span><span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Birch &amp; Bloom (2007; N = 104)"</span>) <span class="sc">+</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_linedraw</span>() <span class="sc">+</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span>.<span class="dv">5</span>),</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> probability_percent <span class="sc">-</span> standard_error,</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> probability_percent <span class="sc">+</span> standard_error), <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="fu">rgb</span>(<span class="dv">101</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">187</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">103</span><span class="sc">/</span><span class="dv">255</span>),</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">rgb</span>(<span class="dv">249</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">170</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">112</span><span class="sc">/</span><span class="dv">255</span>)),</span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Ignorance"</span>, <span class="st">"Knowledge-plausible"</span>)) <span class="sc">+</span></span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Condition"</span>) <span class="sc">+</span></span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Percent of Red"</span>) <span class="sc">+</span></span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">1.5</span>, <span class="at">y =</span> <span class="dv">57</span>, <span class="at">label =</span> <span class="st">"***"</span>, <span class="at">size =</span> <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">xend =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="dv">55</span>, <span class="at">yend =</span> <span class="dv">55</span>),</span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a>               <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">size =</span> <span class="fl">0.5</span>)</span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-24"><a href="#cb55-24" aria-hidden="true" tabindex="-1"></a>plot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Borchers data</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>borchers_replication_all_participants <span class="ot">&lt;-</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_xls</span>(<span class="st">"/Users/ottuba/birch2007_2_rescue/data/borchers_replication_anonymized.xls"</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy data</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>borchers_replication_tidy <span class="ot">&lt;-</span> borchers_replication_all_participants <span class="sc">%&gt;%</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">subid =</span> <span class="fu">row.names</span>(.)) <span class="sc">%&gt;%</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(measurement, probability_pct, red_knowledgeplausible<span class="sc">:</span>blue_ignorance) <span class="sc">%&gt;%</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(probability_pct)) <span class="sc">%&gt;%</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(measurement, <span class="fu">c</span>(<span class="st">"color"</span>, <span class="st">"condition"</span>))</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for releavant participants </span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>borchers_replication_filtered_data <span class="ot">=</span> borchers_replication_tidy <span class="sc">%&gt;%</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(high_school <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="co"># Completed high school</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>         color_blind <span class="sc">==</span> <span class="st">"No"</span>, <span class="co"># Is not colorblind</span></span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>         consent <span class="sc">==</span> <span class="st">"I agree"</span>) <span class="co"># Consented to the study</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Borchers data for red container judgments</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  borchers_replication_filtered_data <span class="sc">%&gt;%</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(color<span class="sc">==</span><span class="st">"red"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> condition, <span class="at">y =</span> probability_pct, <span class="at">fill =</span> condition) <span class="sc">+</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">fun.data =</span> mean_se) <span class="sc">+</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Condition"</span>) <span class="sc">+</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Percent of Red"</span>) <span class="sc">+</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Borchers (2018; N = 73)"</span>) <span class="sc">+</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="fu">rgb</span>(<span class="dv">101</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">187</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">103</span><span class="sc">/</span><span class="dv">255</span>),</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">rgb</span>(<span class="dv">249</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">170</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">112</span><span class="sc">/</span><span class="dv">255</span>)),</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Ignorance"</span>, <span class="st">"Knowledge-plausible"</span>)) <span class="sc">+</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_linedraw</span>() <span class="sc">+</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span>.<span class="dv">5</span>),</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_compare_means</span>(<span class="at">comparisons =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"ignorance"</span>, <span class="st">"knowledgeplausible"</span>)), </span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>                 <span class="at">label =</span> <span class="st">"p.signif"</span>,</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>                 <span class="at">label.size =</span> <span class="dv">24</span>, <span class="at">bracket.size =</span> .<span class="dv">75</span>, <span class="at">label.y =</span> <span class="fu">c</span>(<span class="dv">50</span>,<span class="dv">50</span>))</span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a>plot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot my own data for red container judgments</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  final_data_tidy <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(color <span class="sc">==</span> <span class="st">"red"</span> <span class="sc">&amp;</span> condition <span class="sc">!=</span> <span class="st">"knowimplausible"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> condition, <span class="at">y =</span> probability_pct, <span class="at">fill =</span> condition) <span class="sc">+</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">fun.data =</span> mean_se) <span class="sc">+</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Condition"</span>) <span class="sc">+</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Abutto (2023; N = 374)"</span>) <span class="sc">+</span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Percent of Red"</span>) <span class="sc">+</span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="fu">rgb</span>(<span class="dv">101</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">187</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">103</span><span class="sc">/</span><span class="dv">255</span>),</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">rgb</span>(<span class="dv">249</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">170</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">112</span><span class="sc">/</span><span class="dv">255</span>)),</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Ignorance"</span>, <span class="st">"Knowledge-plausible"</span>)) <span class="sc">+</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_linedraw</span>() <span class="sc">+</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> .<span class="dv">5</span>),</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_compare_means</span>(<span class="at">comparisons =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"ignorance"</span>, <span class="st">"knowplausible"</span>)), </span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>                   <span class="at">label =</span> <span class="st">"p.signif"</span>,</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a>                   <span class="at">label.size =</span> <span class="dv">24</span>, <span class="at">bracket.size =</span> .<span class="dv">75</span>, <span class="at">label.y =</span> <span class="fu">c</span>(<span class="dv">50</span>,<span class="dv">50</span>))</span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a>plot3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Figure 3.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine plots into a single panel</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>combined_plot <span class="ot">&lt;-</span> plot1 <span class="sc">+</span> plot2 <span class="sc">+</span> plot3</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>combined_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="960"></p>
</div>
</div>
</section>
</section>
<section id="exploratory-analyses" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-analyses">Exploratory Analyses</h3>
<p>The plot below provides a graphical comparison of all group contrasts across the present study’s data and the original study’s data (Birch &amp; Bloom, 2007).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">&lt;-</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  final_data_tidy <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">condition =</span> <span class="fu">fct_relevel</span>(condition, </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Knowledge-plausible"</span>, </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Ignorance"</span>, </span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Knowledge-implausible"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> color, <span class="at">y =</span> probability_pct, <span class="at">fill =</span> condition) <span class="sc">+</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>)) <span class="sc">+</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun.data =</span> mean_se, <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>)) <span class="sc">+</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Container"</span>) <span class="sc">+</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Average Probability Rating"</span>) <span class="sc">+</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Abutto (2023; N = 374)"</span>) <span class="sc">+</span></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="fu">rgb</span>(<span class="dv">249</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">170</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">112</span><span class="sc">/</span><span class="dv">255</span>),</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">rgb</span>(<span class="dv">101</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">187</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">103</span><span class="sc">/</span><span class="dv">255</span>),</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">rgb</span>(<span class="dv">167</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">144</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">192</span><span class="sc">/</span><span class="dv">255</span>)),</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Knowledge-plausible"</span>,</span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Ignorance"</span>,</span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Knowledge-implausible"</span>)) <span class="sc">+</span></span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_linedraw</span>() <span class="sc">+</span></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> .<span class="dv">5</span>),</span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">&lt;-</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  birch_bloom_data <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">condition =</span> <span class="fu">fct_relevel</span>(condition, </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Knowledge-plausible"</span>, </span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Ignorance"</span>, </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Knowledge-implausible"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> container, <span class="at">y =</span> probability_percent, <span class="at">fill =</span> condition) <span class="sc">+</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>)) <span class="sc">+</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> probability_percent <span class="sc">-</span> standard_error, </span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> probability_percent <span class="sc">+</span> standard_error),</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>)) <span class="sc">+</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Container"</span>) <span class="sc">+</span></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Average Probability Rating"</span>) <span class="sc">+</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Birch and Bloom (2007; N = 155)"</span>) <span class="sc">+</span></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="fu">rgb</span>(<span class="dv">249</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">170</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">112</span><span class="sc">/</span><span class="dv">255</span>),</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">rgb</span>(<span class="dv">101</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">187</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">103</span><span class="sc">/</span><span class="dv">255</span>),</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">rgb</span>(<span class="dv">167</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">144</span><span class="sc">/</span><span class="dv">255</span>,<span class="dv">192</span><span class="sc">/</span><span class="dv">255</span>)),</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Knowledge-plausible"</span>,</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Ignorance"</span>,</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Knowledge-implausible"</span>)) <span class="sc">+</span></span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_linedraw</span>() <span class="sc">+</span></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> .<span class="dv">5</span>),</span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Figure 4.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>combined_plot2 <span class="ot">&lt;-</span> plot4<span class="sc">+</span>plot5</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>combined_plot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="1152"></p>
</div>
</div>
<p>The code outputs below relate to the present study’s exploratory analyses.</p>
<ol type="1">
<li>Comparison of participants’ probability judgments for the “red” container between the <em>ignorance</em> and <em>knowledge-implausible</em> groups</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(red <span class="sc">~</span> condition,</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> final_data[final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"knowplausible"</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  red by condition
t = 1.0989, df = 246.75, p-value = 0.2729
alternative hypothesis: true difference in means between group ignorance and group knowimplausible is not equal to 0
95 percent confidence interval:
 -1.946352  6.858970
sample estimates:
      mean in group ignorance mean in group knowimplausible 
                      20.4878                       18.0315 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Comparison of participants’ probability judgments for the “blue” container between the <em>ignorance</em> and <em>knowledge-plausible</em> groups</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(blue <span class="sc">~</span> condition,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> final_data[final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"knowimplausible"</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  blue by condition
t = -1.7008, df = 239.15, p-value = 0.09028
alternative hypothesis: true difference in means between group ignorance and group knowplausible is not equal to 0
95 percent confidence interval:
 -13.3408727   0.9780351
sample estimates:
    mean in group ignorance mean in group knowplausible 
                   59.50407                    65.68548 </code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Comparison of participants’ probability judgments for the “blue” container between the <em>ignorance</em> and <em>knowledge-implausible</em> groups</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(blue <span class="sc">~</span> condition,</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> final_data[final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"knowplausible"</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  blue by condition
t = -1.2111, df = 246.31, p-value = 0.227
alternative hypothesis: true difference in means between group ignorance and group knowimplausible is not equal to 0
95 percent confidence interval:
 -12.014787   2.865437
sample estimates:
      mean in group ignorance mean in group knowimplausible 
                     59.50407                      64.07874 </code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Comparison of participants’ probability judgments for the “purple” container between the <em>ignorance</em> and <em>knowledge-implausible</em> groups</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(purple <span class="sc">~</span> condition,</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> final_data[final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"knowplausible"</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  purple by condition
t = -0.97267, df = 218.02, p-value = 0.3318
alternative hypothesis: true difference in means between group ignorance and group knowimplausible is not equal to 0
95 percent confidence interval:
 -5.351820  1.814915
sample estimates:
      mean in group ignorance mean in group knowimplausible 
                     9.601626                     11.370079 </code></pre>
</div>
</div>
</section>
</section>
<section id="summary-and-discussion-of-replication-attempt" class="level2">
<h2 class="anchored" data-anchor-id="summary-and-discussion-of-replication-attempt">Summary and Discussion of Replication Attempt</h2>
<p>The present project set out to replicate Birch and Bloom’s (2007) examination of possible parallels between adults’ and children’s struggles in “false-belief reasoning” when sufficiently sensitive measures are used. To this end, I employed an online version of Birch and Bloom’s (2007) modified version of a classic displacement task and closely matched the authors’ stimuli, procedures, sample demographics, and analyses. The main difference lay in the nature of the study setting (in-lab versus online).</p>
<p>Contrary to the original study by Birch and Bloom, the present results indicated a negligible effect of the “curse of knowledge” bias on adults’ false belief reasoning. More concretely, the analysis showed that even if participants had prior knowledge of the event outcome, and the event outcome in question was plausible, adults did <em>not</em> display greater error rates in reasoning from the perspective of the (unknowing) story protagonist. This was reflected in the statistically negligible difference in probability judgments for the “red” container between the <em>ignorance</em> and <em>knowledge-plausible</em> groups. That is, even if participants knew where the violin had been moved to, and even if the new location of the violin was one where the protagonist (Vicky) might reasonably search, their probability judgments still tended to favor the search location an unknowing agent (i.e., Vicky) would prefer. Similarly, participants in the <em>knowledge-plausible</em> group did not differ in their judgments that Vicky would first search for her violin in the “false-belief” container - the blue container, where Vicky had originally placed her violin - compared to participants who had no knowledge of the violin’s location (<em>ignorance</em> group). With that, the present results did not replicate Birch and Bloom’s (2007) relative decrease in participants’ probability judgments that Vicky would first search for her violin in the “blue” container when comparing participants in the <em>knowledge-plausible and ignorance</em> groups.</p>
<p>Notably, however, the present exploratory analyses replicated other parts of Birch and Bloom’s (2007) findings. When comparing probability judgments for the “red” container between the <em>ignorance</em> and <em>knowledge-implausible</em> groups, the analysis revealed that manipulating just participants’ knowledge of the outcome (i.e., telling participants that the violin was moved to the “purple” container) indeed did not induce higher error rates in adults’ false-belief reasoning.</p>
<p>With that, the present study partially replicated the original findings: Select exploratory results were congruent, but the main findings contradicted the reports from the original study conducted by Birch and Bloom (2007). This pattern of results aligns with the reports from the two previous replication attempts conducted by Bridgers (n.d.) and Borchers (2018).</p>
<section id="mini-meta-analysis" class="level3">
<h3 class="anchored" data-anchor-id="mini-meta-analysis">Mini Meta Analysis</h3>
<p>Combining across the original paper, 1st replication, and 2nd replication, the aggregate effect size is negligible (estimated 5% difference in mean probability judgments on the original scale):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import raw meta-analysis data</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>raw_metaanalysis_data <span class="ot">&lt;-</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="fu">read_xlsx</span>(<span class="st">"/Users/ottuba/birch2007_2_rescue/data/Birch-Bloom_minimeta_data.xlsx"</span>, <span class="at">range =</span> <span class="st">"B2:G6"</span>))</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>raw_metaanalysis_data[,<span class="fu">c</span>(<span class="st">"N"</span>, <span class="st">"raw_mean_difference"</span>,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"raw_low"</span>, <span class="st">"raw_high"</span>)] <span class="ot">&lt;-</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(raw_metaanalysis_data[,<span class="fu">c</span>(<span class="st">"N"</span>, <span class="st">"raw_mean_difference"</span>,</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"raw_low"</span>, <span class="st">"raw_high"</span>)], as.numeric) <span class="co"># Convert to numeric values</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(raw_metaanalysis_data,</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">table.attr =</span> <span class="st">"class=</span><span class="sc">\"</span><span class="st">striped</span><span class="sc">\"</span><span class="st">"</span>,</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">format =</span> <span class="st">"html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="striped table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Study</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Citation</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">raw_mean_difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">raw_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">raw_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Birch and Bloom</td>
<td style="text-align: left;">Birch &amp; Bloom (2007)</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">1.72</td>
<td style="text-align: right;">20.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bridgers</td>
<td style="text-align: left;">Bridgers (n.d.)</td>
<td style="text-align: right;">152</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">-3.23</td>
<td style="text-align: right;">13.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Borchers</td>
<td style="text-align: left;">Borchers (2018)</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">4.09</td>
<td style="text-align: right;">-8.45</td>
<td style="text-align: right;">16.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abutto</td>
<td style="text-align: left;">Abutto (2023)</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">3.48</td>
<td style="text-align: right;">-1.19</td>
<td style="text-align: right;">8.15</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>for_mod <span class="ot">&lt;-</span> raw_metaanalysis_data <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">se=</span>(raw_high<span class="sc">-</span>raw_low)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fl">1.96</span>)) <span class="co"># Calculate SE values</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>mini_meta_mod <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi=</span>raw_mean_difference,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">sei=</span>se, <span class="at">slab=</span>Study, <span class="at">data=</span>for_mod) <span class="co"># Run model</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mini_meta_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 4; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
 -8.1949   16.3898   20.3898   18.5870   32.3898   

tau^2 (estimated amount of total heterogeneity): 0 (SE = 12.1211)
tau (square root of estimated tau^2 value):      0
I^2 (total heterogeneity / total variability):   0.00%
H^2 (total variability / sampling variability):  1.00

Test for Heterogeneity:
Q(df = 3) = 2.0314, p-val = 0.5659

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub     
  4.9261  1.8200  2.7066  0.0068  1.3589  8.4933  ** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>aggregate <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Study=</span><span class="st">"Aggregate"</span>, <span class="at">Citation=</span><span class="cn">NA</span>,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">raw_mean_difference =</span> mini_meta_mod<span class="sc">$</span>b, <span class="co"># Effect of interest</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">raw_low =</span> mini_meta_mod<span class="sc">$</span>ci.lb, <span class="co"># Lower CI bound</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">raw_high =</span> mini_meta_mod<span class="sc">$</span>ci.ub, <span class="co"># Upper CI bound</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">N =</span> <span class="fu">sum</span>(raw_metaanalysis_data<span class="sc">$</span>N)) <span class="co"># N for respective study</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>for_plot <span class="ot">&lt;-</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  raw_metaanalysis_data <span class="sc">%&gt;%</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(aggregate) <span class="sc">%&gt;%</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Study =</span> <span class="fu">factor</span>(Study,</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Aggregate"</span>,</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Birch and Bloom"</span>,</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Bridgers"</span>,</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Borchers"</span>,</span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Abutto"</span>))) <span class="co"># create new column with study names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Figure 5.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot mini meta-analysis results</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(for_plot,</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Study, <span class="at">y =</span> raw_mean_difference,</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">ymin =</span> raw_low, <span class="at">ymax =</span> raw_high, <span class="at">size=</span>N))<span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">colour=</span><span class="st">'darkgray'</span>,<span class="at">size=</span>.<span class="dv">5</span>,<span class="at">width=</span>.<span class="dv">25</span>)<span class="sc">+</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>for_plot <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Study <span class="sc">!=</span> <span class="st">"Aggregate"</span>))<span class="sc">+</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>for_plot <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Study <span class="sc">==</span> <span class="st">"Aggregate"</span>),</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">color =</span> <span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">25</span>, <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_area</span>()<span class="sc">+</span></span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"black"</span>)<span class="sc">+</span></span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_linedraw</span>() <span class="sc">+</span></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">1.5</span>, <span class="at">lty =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Main effect size on original scale"</span>, <span class="at">x =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Note.</em> The estimate for Bridgers may be inaccurate, as it had to be reconstructed based on incomplete information (missing information on the mean difference and SDs relating to the group comparison of interest). The necessary numerical information was reconstructed with the help of ChatGPT (see here for output: <a href="https://chat.openai.com/share/cf52551d-d983-48af-a3a7-3239442fdf9d" class="uri">https://chat.openai.com/share/cf52551d-d983-48af-a3a7-3239442fdf9d</a>).</p>
<p><strong>Figure 6.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run forest plot</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(mini_meta_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Note.</em> The estimate for Bridgers may be inaccurate, as it had to be reconstructed based on incomplete information (missing information on the mean difference and SDs relating to the group comparison of interest). The necessary numerical information was reconstructed with the help of ChatGPT (see here for output: <a href="https://chat.openai.com/share/cf52551d-d983-48af-a3a7-3239442fdf9d" class="uri">https://chat.openai.com/share/cf52551d-d983-48af-a3a7-3239442fdf9d</a>).</p>
<p><strong>Figure 7.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run funnel plot</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(mini_meta_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="scale-ratings" class="level4">
<h4 class="anchored" data-anchor-id="scale-ratings">Scale Ratings</h4>
<p><em>Using a 0-1 scale rating [0, .25, .5, .75, 1], how well did this rescue replicate the original results?</em></p>
<p>On the above scale, I would rate the present rescue’s replication of results a .25. There was no support for the original authors’ main findings, but results on comparisons of secondary interest aligned.</p>
<p><em>Categorize your rescue for how close of a replication of the original it was using the scale in the Figure below:</em></p>
<p>Based on the scale provided in the figure below, I would rate the present rescue a “very close replication.” The effect and hypothesis in question were the same, the conceptualization and operationalization of IVs and DVs were held constant, the population was largely matched (pre-screened for adults living in the U.S. and enrolled in college), and stimuli were adapted only slightly. The key difference lay in the (lack of a) physical setting.</p>
<p><strong>Figure 8.</strong></p>
<p><img src="images/Screenshot%202023-12-12%20at%2019.07.18.png" class="img-fluid"></p>
<p><em>Note.</em> Figure taken from LeBel et al.&nbsp;(2018).</p>
</section>
</section>
<section id="commentary" class="level3">
<h3 class="anchored" data-anchor-id="commentary">Commentary</h3>
<p>Crucially, the present rescue project’s results showed that different participants in different conditions were largely consistent in how probable they thought it was for Vicky to first search in the “red” container. In other words, rather than experiencing different degrees of interference as per the “curse of knowledge,” participants seemed to consistently consider the “red” container - that is, the container located where Vicky first put her violin - a plausible option for Vicky to start her search. Indeed, even in the <em>knowledge plausible</em> condition, one can (successfully) reason from the unknowing protagonist’s perspective and still think the “red” container presents a reasonable choice: It represents the same location - albeit not the same container - as where Vicky first put her violin before leaving the room. While it is certainly plausible for Vicky to distinctly remember the color of the container she put her violin (i.e., blue) and first begin her search there, it is also plausible for her to distinctly remember the corner of the living room she put her violin (i.e., where the red container is), and first begin her search there. Thus, using probability judgments relating to the “red” container as a basis for estimating the effect of the “curse of knowledge” bias may be misguided in its premise that unknowing Vicky would not reasonably begin her search there.</p>
<p>It should also be noted that relative to Birch and Bloom’s (2007) original results, participants also generally judged it more probable for Vicky to first search in the “green” or “purple” containers. In the present study, descriptive statistics showed <span class="math inline">\(M_{green}\)</span> = 7.3% and <span class="math inline">\(SD_{green}\)</span> = 9.8% as well as <span class="math inline">\(M_{purple}\)</span> = 8.8% and <span class="math inline">\(SD_{purple}\)</span> = 13.2%. In the original study, descriptive statistics showed <span class="math inline">\(M_{green}\)</span> = 3.3% and <span class="math inline">\(SD_{green}\)</span>, as well as <span class="math inline">\(M_{purple}\)</span> = 3.7% and <span class="math inline">\(SD_{purple}\)</span> = 6.3%. This is slightly surprising, given that the story context should render these search locations as quite improbable: Both containers are neither of the same color as the container where Vicky placed her violin (blue), nor do they inhabit the same location of the original container after the sister, Denise, had rearranged the room. Upon a closer examination of the respective data columns, I found that a considerable number of participants assigned the “purple” and “green” containers unexpectedly high probabilities, with <em>n</em> = 49 and <em>n</em> = 40 participants at ≥ 25%, respectively. While the result of the key test does not change upon excluding said participants (see Appendix), this overall pattern is still a considerable deviation from the original results.</p>
<p>Importantly, all of the above is still consistent with the explanation that <em>some</em> but not all adults in the <em>knowledge-plausible</em> condition may have succumbed to a “curse of knowledge” bias under the circumstances leveraged in the present study. The estimated effect size across replication studies (see Figures 7 and 8), though drastically smaller than the one estimated in the original study (<em>d</em> = .47). This difference in effect size is likely, at least in part, attributable to sampling variability as well as the discrepancies in study setup (lab versus in-person). Hence, Birch and Bloom’s (2007) fundamental claim that adults may display difficulties in their false-belief reasoning if sensitive enough measures are used should not be dismissed entirely on the basis of the present study’s results. Rather than asking whether or not the “curse of knowledge” is a true phenomenon, the key question then becomes: To what degree, and under which circumstances, if not the ones induced in the present study, do adults display difficulties in false-belief reasoning akin to those of children? Future research may wish to develop and employ new, adapted paradigms to investigate this question.</p>
</section>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">Appendix</h2>
<p>Re-running key test while excluding participants with unexpectedly high probability judgments for “green” and “purple” containers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(red <span class="sc">~</span> condition,</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> final_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>         final_data<span class="sc">$</span>condition <span class="sc">!=</span> <span class="st">"knowimplausible"</span>,</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>         final_data<span class="sc">$</span>green <span class="sc">&lt;=</span> <span class="dv">25</span>,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>         final_data<span class="sc">$</span>purple <span class="sc">&lt;=</span> <span class="dv">25</span>,</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>         ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  red by condition
t = -1.533, df = 228.76, p-value = 0.1267
alternative hypothesis: true difference in means between group ignorance and group knowplausible is not equal to 0
95 percent confidence interval:
 -8.517755  1.063370
sample estimates:
    mean in group ignorance mean in group knowplausible 
                   20.12281                    23.85000 </code></pre>
</div>
</div>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Birch, S. A. J., &amp; Bloom, P. (2007). The Curse of Knowledge in Reasoning About False Beliefs. <em>Psychological Science</em>, <em>18</em>(5), 382–386. <a href="https://doi.org/10.1111/j.1467-9280.2007.01909.x" class="uri">https://doi.org/10.1111/j.1467-9280.2007.01909.x</a></p>
<p>Borchers, L. R. Replication of Study The Curse of Knowledge in Reasoning About False Beliefs by Susan A.J. Birch &amp; Paul Bloom (2007, Psychological Science). RPubs. Retrieved on December 12, 2023, from <a href="https://rpubs.com/lrborchers/450894" class="uri">https://rpubs.com/lrborchers/450894</a></p>
<p>Bridgers, S. (n.d.). Replication of ‘The Curse of Knowledge in Reasoning about False Beliefs’&nbsp; by Susan A.J. Birch &amp; Paul Bloom (2007, Psychological Science). Google Docs. Retrieved on December 12, 2023, from <a href="https://docs.google.com/document/d/1fSARliH5QKadGy3UElC00ehgwr2LLQbey-uzb1RPv0A/edit?usp=embed_facebook" class="uri">https://docs.google.com/document/d/1fSARliH5QKadGy3UElC00ehgwr2LLQbey-uzb1RPv0A/edit?usp=embed_facebook</a></p>
<p>LeBel, E. P., McCarthy, R. J., Earp, B. D., Elson, M., &amp; Vanpaemel, W. (2018). A unified framework to quantify the credibility of scientific findings. <em>Advances in Methods and Practices in Psychological Science</em>, <em>1</em>(3), 389–402. <a href="https://doi.org/10.1177/2515245918787489" class="uri">https://doi.org/10.1177/2515245918787489</a></p>
<p>Livingston, L. A., Shah, P., White, S. J., &amp; Happé, F. (2021). Further developing the Frith–Happé animations: A quicker, more objective, and web-based test of theory of mind for autistic and neurotypical adults. <em>Autism Research</em>, <em>14</em>(9), 1905–1912. <a href="https://doi.org/10.1002/aur.2575" class="uri">https://doi.org/10.1002/aur.2575</a></p>
<p>Simonsohn, U. (2014). <em>Small Telescopes: Detectability and the Evaluation of Replication Results</em> (SSRN Scholarly Paper 2259879). <a href="https://doi.org/10.2139/ssrn.2259879" class="uri">https://doi.org/10.2139/ssrn.2259879</a></p>
<p>Wimmer, H., &amp; Perner, J. (1983). Beliefs about beliefs: Representation and constraining function of wrong beliefs in young children’s understanding of deception. <em>Cognition</em>, <em>13</em>(1), 103–128. <a href="https://doi.org/10.1016/0010-0277(83)90004-5" class="uri">https://doi.org/10.1016/0010-0277(83)90004-5</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>